openapi-generator-cli generate -i ../timetrekah/timetrekah/schema.yaml -o ./autogenerated_client -g javascript

npm i ./autogenerated_client

mv ./autogenerated_client/src ./src/client

rm -r ./autogenerated_client
