/**
 * Timetrekah API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PasswordResetConfirm model module.
 * @module model/PasswordResetConfirm
 * @version 0.1.0
 */
class PasswordResetConfirm {
    /**
     * Constructs a new <code>PasswordResetConfirm</code>.
     * @alias module:model/PasswordResetConfirm
     * @param uid {String} 
     * @param token {String} 
     * @param newPassword {String} 
     */
    constructor(uid, token, newPassword) { 
        
        PasswordResetConfirm.initialize(this, uid, token, newPassword);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, uid, token, newPassword) { 
        obj['uid'] = uid;
        obj['token'] = token;
        obj['new_password'] = newPassword;
    }

    /**
     * Constructs a <code>PasswordResetConfirm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PasswordResetConfirm} obj Optional instance to populate.
     * @return {module:model/PasswordResetConfirm} The populated <code>PasswordResetConfirm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PasswordResetConfirm();

            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('new_password')) {
                obj['new_password'] = ApiClient.convertToType(data['new_password'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PasswordResetConfirm</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PasswordResetConfirm</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PasswordResetConfirm.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['uid'] && !(typeof data['uid'] === 'string' || data['uid'] instanceof String)) {
            throw new Error("Expected the field `uid` to be a primitive type in the JSON string but got " + data['uid']);
        }
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }
        // ensure the json data is a string
        if (data['new_password'] && !(typeof data['new_password'] === 'string' || data['new_password'] instanceof String)) {
            throw new Error("Expected the field `new_password` to be a primitive type in the JSON string but got " + data['new_password']);
        }

        return true;
    }


}

PasswordResetConfirm.RequiredProperties = ["uid", "token", "new_password"];

/**
 * @member {String} uid
 */
PasswordResetConfirm.prototype['uid'] = undefined;

/**
 * @member {String} token
 */
PasswordResetConfirm.prototype['token'] = undefined;

/**
 * @member {String} new_password
 */
PasswordResetConfirm.prototype['new_password'] = undefined;






export default PasswordResetConfirm;

