/**
 * Timetrekah API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SetPassword model module.
 * @module model/SetPassword
 * @version 0.1.0
 */
class SetPassword {
    /**
     * Constructs a new <code>SetPassword</code>.
     * @alias module:model/SetPassword
     * @param newPassword {String} 
     * @param currentPassword {String} 
     */
    constructor(newPassword, currentPassword) { 
        
        SetPassword.initialize(this, newPassword, currentPassword);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, newPassword, currentPassword) { 
        obj['new_password'] = newPassword;
        obj['current_password'] = currentPassword;
    }

    /**
     * Constructs a <code>SetPassword</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SetPassword} obj Optional instance to populate.
     * @return {module:model/SetPassword} The populated <code>SetPassword</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SetPassword();

            if (data.hasOwnProperty('new_password')) {
                obj['new_password'] = ApiClient.convertToType(data['new_password'], 'String');
            }
            if (data.hasOwnProperty('current_password')) {
                obj['current_password'] = ApiClient.convertToType(data['current_password'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SetPassword</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SetPassword</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SetPassword.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['new_password'] && !(typeof data['new_password'] === 'string' || data['new_password'] instanceof String)) {
            throw new Error("Expected the field `new_password` to be a primitive type in the JSON string but got " + data['new_password']);
        }
        // ensure the json data is a string
        if (data['current_password'] && !(typeof data['current_password'] === 'string' || data['current_password'] instanceof String)) {
            throw new Error("Expected the field `current_password` to be a primitive type in the JSON string but got " + data['current_password']);
        }

        return true;
    }


}

SetPassword.RequiredProperties = ["new_password", "current_password"];

/**
 * @member {String} new_password
 */
SetPassword.prototype['new_password'] = undefined;

/**
 * @member {String} current_password
 */
SetPassword.prototype['current_password'] = undefined;






export default SetPassword;

