/**
 * Timetrekah API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SetUsernameRequest model module.
 * @module model/SetUsernameRequest
 * @version 0.1.0
 */
class SetUsernameRequest {
    /**
     * Constructs a new <code>SetUsernameRequest</code>.
     * @alias module:model/SetUsernameRequest
     * @param currentPassword {String} 
     * @param newUsername {String} Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_.
     */
    constructor(currentPassword, newUsername) { 
        
        SetUsernameRequest.initialize(this, currentPassword, newUsername);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, currentPassword, newUsername) { 
        obj['current_password'] = currentPassword;
        obj['new_username'] = newUsername;
    }

    /**
     * Constructs a <code>SetUsernameRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SetUsernameRequest} obj Optional instance to populate.
     * @return {module:model/SetUsernameRequest} The populated <code>SetUsernameRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SetUsernameRequest();

            if (data.hasOwnProperty('current_password')) {
                obj['current_password'] = ApiClient.convertToType(data['current_password'], 'String');
            }
            if (data.hasOwnProperty('new_username')) {
                obj['new_username'] = ApiClient.convertToType(data['new_username'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SetUsernameRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SetUsernameRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SetUsernameRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['current_password'] && !(typeof data['current_password'] === 'string' || data['current_password'] instanceof String)) {
            throw new Error("Expected the field `current_password` to be a primitive type in the JSON string but got " + data['current_password']);
        }
        // ensure the json data is a string
        if (data['new_username'] && !(typeof data['new_username'] === 'string' || data['new_username'] instanceof String)) {
            throw new Error("Expected the field `new_username` to be a primitive type in the JSON string but got " + data['new_username']);
        }

        return true;
    }


}

SetUsernameRequest.RequiredProperties = ["current_password", "new_username"];

/**
 * @member {String} current_password
 */
SetUsernameRequest.prototype['current_password'] = undefined;

/**
 * Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_.
 * @member {String} new_username
 */
SetUsernameRequest.prototype['new_username'] = undefined;






export default SetUsernameRequest;

