/**
 * Timetrekah API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Title model module.
 * @module model/Title
 * @version 0.1.0
 */
class Title {
    /**
     * Constructs a new <code>Title</code>.
     * @alias module:model/Title
     * @param id {Number} 
     * @param name {String} 
     * @param startDate {Date} 
     * @param activity {Number} 
     */
    constructor(id, name, startDate, activity) { 
        
        Title.initialize(this, id, name, startDate, activity);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, startDate, activity) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['start_date'] = startDate;
        obj['activity'] = activity;
    }

    /**
     * Constructs a <code>Title</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Title} obj Optional instance to populate.
     * @return {module:model/Title} The populated <code>Title</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Title();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], 'String');
            }
            if (data.hasOwnProperty('start_date')) {
                obj['start_date'] = ApiClient.convertToType(data['start_date'], 'Date');
            }
            if (data.hasOwnProperty('end_date')) {
                obj['end_date'] = ApiClient.convertToType(data['end_date'], 'Date');
            }
            if (data.hasOwnProperty('activity')) {
                obj['activity'] = ApiClient.convertToType(data['activity'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Title</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Title</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Title.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['image'] && !(typeof data['image'] === 'string' || data['image'] instanceof String)) {
            throw new Error("Expected the field `image` to be a primitive type in the JSON string but got " + data['image']);
        }

        return true;
    }


}

Title.RequiredProperties = ["id", "name", "start_date", "activity"];

/**
 * @member {Number} id
 */
Title.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Title.prototype['name'] = undefined;

/**
 * @member {String} description
 */
Title.prototype['description'] = undefined;

/**
 * @member {String} image
 */
Title.prototype['image'] = undefined;

/**
 * @member {Date} start_date
 */
Title.prototype['start_date'] = undefined;

/**
 * @member {Date} end_date
 */
Title.prototype['end_date'] = undefined;

/**
 * @member {Number} activity
 */
Title.prototype['activity'] = undefined;






export default Title;

