/**
 * Timetrekah API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UsernameResetConfirm model module.
 * @module model/UsernameResetConfirm
 * @version 0.1.0
 */
class UsernameResetConfirm {
    /**
     * Constructs a new <code>UsernameResetConfirm</code>.
     * @alias module:model/UsernameResetConfirm
     * @param newUsername {String} Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_.
     */
    constructor(newUsername) { 
        
        UsernameResetConfirm.initialize(this, newUsername);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, newUsername) { 
        obj['new_username'] = newUsername;
    }

    /**
     * Constructs a <code>UsernameResetConfirm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsernameResetConfirm} obj Optional instance to populate.
     * @return {module:model/UsernameResetConfirm} The populated <code>UsernameResetConfirm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsernameResetConfirm();

            if (data.hasOwnProperty('new_username')) {
                obj['new_username'] = ApiClient.convertToType(data['new_username'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UsernameResetConfirm</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsernameResetConfirm</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UsernameResetConfirm.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['new_username'] && !(typeof data['new_username'] === 'string' || data['new_username'] instanceof String)) {
            throw new Error("Expected the field `new_username` to be a primitive type in the JSON string but got " + data['new_username']);
        }

        return true;
    }


}

UsernameResetConfirm.RequiredProperties = ["new_username"];

/**
 * Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_.
 * @member {String} new_username
 */
UsernameResetConfirm.prototype['new_username'] = undefined;






export default UsernameResetConfirm;

